name: Build a Debian package using an overlay recipe
'on':
  workflow_dispatch:
    inputs:
      config:
        description: Path to the YAML configuration file
        required: true
        type: string
jobs:
  build:
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ inputs.config }}
    container:
      image: public.ecr.aws/debian/debian:trixie
      options: --privileged
    steps:
    - name: Update OS packages
      run: 'set -ux

        apt update

        DEBIAN_FRONTEND=noninteractive apt -y upgrade

        DEBIAN_FRONTEND=noninteractive apt -y full-upgrade

        '
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Install sbuild and dependencies
      run: "set -ux\nDEBIAN_FRONTEND=noninteractive \\\n    apt -y install --no-install-recommends\
        \ \\\n        sudo sbuild gnupg debootstrap debian-archive-keyring schroot\n"
    - name: Set up sbuild user
      run: 'set -ux

        useradd -m builder

        echo ''builder ALL=(ALL) NOPASSWD:ALL'' >> /etc/sudoers

        mkdir -p /etc/sbuild

        echo ''builder'' > /etc/sbuild/buildd.conf

        sbuild-adduser builder

        '
    - name: Create sbuild chroot for target suite
      run: "set -ux\n# to read yaml config\nDEBIAN_FRONTEND=noninteractive \\\n  \
        \  apt -y install --no-install-recommends python3 python3-yaml\n# read suite\
        \ from yaml\nsuite=\"$(python3 -c \"import os, yaml; print(yaml.safe_load(open(os.environ['CONFIG']))['suite'])\"\
        )\"\n# defaults args\nextra_repo=\"\"\ndebootstrap_suite=\"${suite}\"\nchroot_prefix=\"\
        \"\nif [ \"${suite}\" = experimental ]; then\n    # special extra args for\
        \ experimental\n    debootstrap_suite='unstable'\n    extra_repo='--extra-repository=deb\
        \   http://deb.debian.org/debian  experimental main'\n    chroot_prefix='--chroot-prefix=experimental'\n\
        fi\nsudo sbuild-createchroot --include=eatmydata,ccache \\\n    ${extra_repo:+\"\
        ${extra_repo}\"} \\\n    ${chroot_prefix:+\"${chroot_prefix}\"} \\\n    \"\
        ${debootstrap_suite}\" \\\n    \"/srv/chroot/${suite}-${{ matrix.runs_on }}-sbuild\"\
        \ \\\n    http://deb.debian.org/debian\n"
    - name: Download and build deb package
      run: "set -ux\n# install dependencies\nDEBIAN_FRONTEND=noninteractive \\\n \
        \   apt -y install --no-install-recommends \\\n        build-essential \\\n\
        \        debian-keyring \\\n        devscripts \\\n        debhelper \\\n\
        \        git \\\n        patch \\\n        python3 \\\n        python3-yaml\n\
        # create output dir\nmkdir -v upload\nchmod a+rw upload\nsudo -u builder python3\
        \ scripts/build-deb.py \\\n    --config \"$CONFIG\" --output-dir upload\n"
    - name: Upload as private artifacts
      uses: qualcomm-linux/upload-private-artifact-action@aws-v4
      with:
        path: upload
        s3_bucket: qcom-prd-gh-artifacts
        destination: ${{ github.repository_owner }}/${{ github.event.repository.name
          }}/${{ github.run_id }}-${{ github.run_attempt }}/
