name: Build U-Boot for RB1
'on':
  schedule:
  - cron: 30 6 * * 1
  workflow_dispatch: null
permissions:
  contents: read
env:
  BUILD_ID: ${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt
    }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-u-boot-rb1:
    if: github.repository == 'qualcomm-linux/qcom-deb-images' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/debian/debian:trixie
      volumes:
      - /efs/qli/qcom-deb-images:/efs
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Update OS packages
      run: 'set -ux

        apt update

        apt -y upgrade

        apt -y full-upgrade

        '
    - name: Build U-Boot Android boot image for RB1
      run: "set -ux\n# install build-dependencies\napt -y install git crossbuild-essential-arm64\
        \ make bison flex bc \\\n    libssl-dev gnutls-dev xxd coreutils gzip mkbootimg\
        \ fwupd\nscripts/build-u-boot-rb1.sh\n"
    - name: Stage artifacts for upload
      run: "set -ux\nmkdir -v artifacts\ncp -av \\\n    u-boot/u-boot-nodtb.bin.gz\
        \ \\\n    u-boot/dts/upstream/src/arm64/qcom/qrb2210-rb1.dtb \\\n    u-boot/u-boot-nodtb.bin.gz-dtb\
        \ \\\n    u-boot/u-boot.bin \\\n    u-boot/rb1-boot.img \\\n    u-boot/u-boot-cap.bin\
        \ \\\n    u-boot/u-boot.cab \\\n    artifacts\n"
    - name: Upload results to EFS
      run: 'set -ux

        export BUILD_DIR="/efs/${BUILD_ID}"

        mkdir -vp "${BUILD_DIR}"

        cp -av artifacts/* "${BUILD_DIR}"

        # create or update u-boot-rb1-latest symlink

        ln -fnsv "${BUILD_ID}" /efs/u-boot-rb1-latest

        # perhaps help NFS sync

        sync

        '
    - name: Upload private artifacts
      uses: qualcomm-linux/upload-private-artifact-action@aws-v4
      id: upload_artifacts
      with:
        path: artifacts
        s3_bucket: qcom-prd-gh-artifacts
        destination: ${{ github.repository_owner }}/${{ github.event.repository.name
          }}/${{ github.run_id }}-${{ github.run_attempt }}/
